### PR TITLE
updated examples README.md

### PR DESCRIPTION
**Pull request by jzcwong**
updated examples README.md

### CODE REVIEW

**Comment by chianw** [comment]
@Azure/avm-core-team-technical - are you able to review this PR? the lint test is failing because of main.telemetry.tf where is says tags are supported for resource "azurerm_resource_group_template_deployment" "telemetry" but not set 
image

Also I've set the necessary environment variables in Github actions but not sure why the Azure Login action is still failing. I'm able to do terraform init, plan and apply in my example directory successfully. 
image

**Comment by segraef** [comment]
> @Azure/avm-core-team-technical - are you able to review this PR? the lint test is failing because of main.telemetry.tf where is says tags are supported for resource "azurerm_resource_group_template_deployment" "telemetry" but not set image
> 
> Also I've set the necessary environment variables in Github actions but not sure why the Azure Login action is still failing. I'm able to do terraform init, plan and apply in my example directory successfully. image

Thanks for mergin the latest grept PR which I can see fixed several of your linter issues :)
Let me have a look at your e2e now.

**Review by segraef — APPROVED** [review]
lgtm

**Review by segraef — DISMISSED** [review]
lgtm

**Review by segraef — CHANGES_REQUESTED** [review]
Need to wait for e2e to complete
please also rebase your branch with latest main, I did a test run with my rebased branch and it works see https://github.com/Azure/terraform-azurerm-avm-res-network-privatednszone/actions/runs/7957064475/job/21719043673

**Review by segraef — APPROVED** [review]
Approving for now but please make sure to test [interfaces](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr24---category-testing---testing-child-extension--interface-resources) if required, thanks.

**Pull request merged**
