### PR TITLE
Update the azurerm version contraint from 4.0 to 5.0

### LINKED ISSUE #81: [AVM Module Issue]: Update the azurerm version contraint from 4.0 to 5.0
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

_No response_

### (Optional) Correlation Id

_No response_

### Description

Update the azurerm version contraint from 4.0 to 5.0

### PR DESCRIPTION
**Pull request by JamesDLD**
## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [x] Someone has opened a bug report issue, and I have included "Closes #81" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [ ] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by chianw** [comment]
Hi @JamesDLD - the linting test is failing because of the change of address_prefix to address_prefixes in azurerm 4.0 and above, for subnet declaration under resource "azurerm_virtual_network"

Before azurerm 4.0 , for example in 3.116.0 https://registry.terraform.io/providers/hashicorp/azurerm/3.116.0/docs/resources/virtual_network , 

image


In azurerm 4.0 - https://registry.terraform.io/providers/hashicorp/azurerm/4.0.0/docs/resources/virtual_network

image


To pass the linting test, are you able to modify main.tf in the examples/default folder to use something like 

`
# create first sample virtual network
resource "azurerm_virtual_network" "vnet1" {
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.avmrg.location
  name                = "vnet1"
  resource_group_name = azurerm_resource_group.avmrg.name

  subnet {
    address_prefixes = ["10.0.1.0/24"]
    name           = "subnet1"
  }
}

# create second sample virtual network
resource "azurerm_virtual_network" "vnet2" {
  address_space       = ["10.1.0.0/16"]
  location            = azurerm_resource_group.avmrg.location
  name                = "vnet2"
  resource_group_name = azurerm_resource_group.avmrg.name

  subnet {
    address_prefixes = ["10.1.1.0/24"]
    name           = "subnet2"
  }
}

`

**Comment by JamesDLD** [comment]
Hi @chianw Yes, I got it! Will update my PR soon, I had to review the avm script to make it work in my context:
- behind a proxy
- ssl inspection
- need to source the docker image from an internal registry

By the way, on which repo can I propose an update of the avm script ?

**Comment by chianw** [comment]
> Hi @chianw Yes, I got it! Will update my PR soon, I had to review the avm script to make it work in my context:
> 
> * behind a proxy
> * ssl inspection
> * need to source the docker image from an internal registry
> 
> By the way, on which repo can I propose an update of the avm script ?

HI @JamesDLD thanks. You can propose changes to the avm script at https://github.com/Azure/terraform-azurerm-avm-template

**Comment by JamesDLD** [comment]
Just did it [here](https://github.com/Azure/terraform-azurerm-avm-template/pull/167) for info, thanks

**Comment by JamesDLD** [comment]
Hi @chianw any chance to have a new git tag including this release?
Thank you

**Comment by chianw** [comment]
> Hi @chianw any chance to have a new git tag including this release? Thank you

Hi @JamesDLD - thanks I just published a new release https://github.com/Azure/terraform-azurerm-avm-res-network-privatednszone/releases/tag/v0.2.2

**Pull request merged**
